### ISSUE TITLE
Allow the display of Buff actions on the HUD.

### ISSUE THREAD

**Issue by Sailor-Munder** [KitCat420/enhancedcombathud-pf1#12]
I don't know if this is possible, but it would be very useful to have. It could be a different section on the HUD that displays only activated buffs actions. I imagine some people use buff actions for different effects (I know I do), like implementing "Call lightning".

**Comment by KitCat420** [comment]
I think this would probably be most effectively done via a normal useable feature that activates the buff via script call.

This is the one I commonly use:
```
const buff = actor.items.get("<buffId>");
buff.update({system: {active: true}});
```
