### ISSUE TITLE
Unchained Action Economy support.

### ISSUE THREAD

**Issue by Sailor-Munder** [KitCat420/enhancedcombathud-pf1#2]
Title says it all. Would be awesome!

**Comment by KitCat420** [comment]
I'll get that checked out. I haven't really ever bothered to read the Unchained Action Economy rules before, but from a quick glance over them, it doesn't look like it would be too much trouble to implement.

**Comment by KitCat420** [comment]
I've implemented support for this in [v0.9.3](https://github.com/KitCat420/enhancedcombathud-pf1/releases/tag/v0.9.3) now. As stated before I've never actually used the Unchained Action Economy, so if you spot any wrongdoings, feel free to open another issue and I'll get them addressed.
